In [1]:
import distrib_zoo as dz
import torch
from layers import *
from func import *
import torch
from torch.nn import functional as F
import numpy as np
import math

In [2]:
glow = Glow(3, 6, 8, 4)

In [3]:
x = torch.rand([3,3])
cond = torch.rand([7,6])
seg_ids = [2,2,3]
x.size(-1)

3

In [6]:
glow.sample(x, cond, seg_ids)

tensor([[-0.1964, -2.6946,  0.8397],
        [-0.8974, -1.2257,  0.7164],
        [-1.8634,  0.1349, -0.7112]], grad_fn=<AddBackward0>)

In [51]:
b = dz.InvLinear(7, 5)

In [53]:
b.flow(a)

tensor([[-0.5545, -1.5532, -0.2023,  1.3605,  0.9206, -0.9471,  0.8023],
        [-0.5545, -1.5532, -0.2023,  1.3605,  0.9206, -0.9471,  0.8023],
        [-0.5545, -1.5532, -0.2023,  1.3605,  0.9206, -0.9471,  0.8023]],
       grad_fn=<MmBackward>)

In [58]:
F.linear(a, torch.rand([5,7]))

tensor([[3.1820, 4.1477, 2.7423, 3.8388, 3.6860],
        [3.1820, 4.1477, 2.7423, 3.8388, 3.6860],
        [3.1820, 4.1477, 2.7423, 3.8388, 3.6860]])

In [56]:
a.shape

torch.Size([3, 7])

In [3]:
a

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [4]:
torch.sum(a, dim=-1)

tensor([7., 7., 7.])

In [5]:
torch.cat((a, a), dim=-1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

tensor([0., 0., 0., 0., 0.])

In [14]:
nn.ReLU()(a)

tensor([[0.6776, 0.3710, 0.8945, 0.8784],
        [0.4639, 0.4442, 0.4395, 0.0650],
        [0.8493, 0.2488, 0.9899, 0.1586],
        [0.7743, 0.2697, 0.1206, 0.9328],
        [0.9514, 0.9723, 0.8638, 0.8053],
        [0.4224, 0.0471, 0.0620, 0.1813],
        [0.8320, 0.7917, 0.9346, 0.3507]])

In [15]:
F.relu(a)

tensor([[0.6776, 0.3710, 0.8945, 0.8784],
        [0.4639, 0.4442, 0.4395, 0.0650],
        [0.8493, 0.2488, 0.9899, 0.1586],
        [0.7743, 0.2697, 0.1206, 0.9328],
        [0.9514, 0.9723, 0.8638, 0.8053],
        [0.4224, 0.0471, 0.0620, 0.1813],
        [0.8320, 0.7917, 0.9346, 0.3507]])

In [22]:
from torch_scatter import *

In [23]:
seg_ids = [0,0,1,1,1,2,2]

In [24]:
scatter_add(F.relu(a), torch.tensor(seg_ids), dim=0)

tensor([[1.1415, 0.8152, 1.3340, 0.9433],
        [2.5749, 1.4907, 1.9743, 1.8967],
        [1.2544, 0.8388, 0.9966, 0.5320]])

In [19]:
?scatter_add

Signature: scatter_add(src, index, dim=-1, out=None, dim_size=None, fill_value=0)
Docstring:
|

.. image:: https://raw.githubusercontent.com/rusty1s/pytorch_scatter/
        master/docs/source/_figures/add.svg?sanitize=true
    :align: center
    :width: 400px

|

Sums all values from the :attr:`src` tensor into :attr:`out` at the indices
specified in the :attr:`index` tensor along a given axis :attr:`dim`. For
each value in :attr:`src`, its output index is specified by its index in
:attr:`input` for dimensions outside of :attr:`dim` and by the
corresponding value in :attr:`index` for dimension :attr:`dim`. If
multiple indices reference the same location, their **contributions add**.

Formally, if :attr:`src` and :attr:`index` are n-dimensional tensors with
size :math:`(x_0, ..., x_{i-1}, x_i, x_{i+1}, ..., x_{n-1})` and
:attr:`dim` = `i`, then :attr:`out` must be an n-dimensional tensor with
size :math:`(x_0, ..., x_{i-1}, y, x_{i+1}, ..., x_{n-1})`. Moreover, the
values of :attr:`ind

In [21]:
?torch.index_add

Docstring: <no docstring>
Type:      builtin_function_or_method


In [11]:
a = [2,3,4]

In [12]:
for i in reversed(list(zip(a, a, a))):
    print(i)

(4, 4, 4)
(3, 3, 3)
(2, 2, 2)


In [7]:
?zip

Init signature: zip(self, /, *args, **kwargs)
Docstring:     
zip(iter1 [,iter2 [...]]) --> zip object

Return a zip object whose .__next__() method returns a tuple where
the i-th element comes from the i-th iterable argument.  The .__next__()
method continues until the shortest iterable in the argument sequence
is exhausted and then it raises StopIteration.
Type:           type
Subclasses:     
