In [1]:
import distrib_zoo as dz
import torch
from layers import *
from func import *
import torch
from torch.nn import functional as F
import numpy as np
import math

In [2]:
glow = Glow(3, 6, 8, 4, [1,2])

In [3]:
x = torch.rand([3,3])
cond = torch.rand([7,6])
seg_ids = [2,2,3]
x.size(-1)

3

In [4]:
affine_F = SimpleLinear(
    8,
    8,
    2
)
affine_G = SimpleLinear(
    7,
    8,
    4
)

In [5]:
nice = Nice(affine_F, affine_G, [1,2]) 

In [6]:
nice.likelihood(x, cond, seg_ids)

(tensor([[1.0597, 0.4525, 1.8302],
         [0.9363, 0.5432, 0.6319],
         [1.5743, 1.0123, 1.0401]], grad_fn=<CatBackward>),
 tensor([ 0.2147, -0.1073, -0.0350], grad_fn=<MulBackward0>))

In [6]:
glow.likelihood(x, cond, seg_ids)

tensor([6.5157, 5.9833, 6.2127], grad_fn=<AddBackward0>)

In [40]:
a = torch.rand([7,4])
b = torch.rand([7,1])

In [41]:
a = a[:3]
a

tensor([[0.0964, 0.2835, 0.3648, 0.0796],
        [0.9032, 0.4627, 0.6628, 0.8152],
        [0.4207, 0.7454, 0.4469, 0.7976]])

In [43]:
torch.repeat_interleave(a, torch.tensor([2,3,3]), dim=0)

tensor([[0.0964, 0.2835, 0.3648, 0.0796],
        [0.0964, 0.2835, 0.3648, 0.0796],
        [0.9032, 0.4627, 0.6628, 0.8152],
        [0.9032, 0.4627, 0.6628, 0.8152],
        [0.9032, 0.4627, 0.6628, 0.8152],
        [0.4207, 0.7454, 0.4469, 0.7976],
        [0.4207, 0.7454, 0.4469, 0.7976],
        [0.4207, 0.7454, 0.4469, 0.7976]])

In [35]:
?a.repeat

Docstring:
repeat(*sizes) -> Tensor

Repeats this tensor along the specified dimensions.

Unlike :meth:`~Tensor.expand`, this function copies the tensor's data.

.. warning::

    :func:`torch.repeat` behaves differently from
    `numpy.repeat <https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html>`_,
    but is more similar to
    `numpy.tile <https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html>`_.
    For the operator similar to `numpy.repeat`, see :func:`torch.repeat_interleave`.

Args:
    sizes (torch.Size or int...): The number of times to repeat this tensor along each
        dimension

Example::

    >>> x = torch.tensor([1, 2, 3])
    >>> x.repeat(4, 2)
    tensor([[ 1,  2,  3,  1,  2,  3],
            [ 1,  2,  3,  1,  2,  3],
            [ 1,  2,  3,  1,  2,  3],
            [ 1,  2,  3,  1,  2,  3]])
    >>> x.repeat(4, 2, 1).size()
    torch.Size([4, 2, 3])
Type:      builtin_function_or_method


In [46]:
torch.split(a, a.size(1) // 2, -1)

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]), tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]), tensor([[1.],
         [1.],
         [1.]]))

In [49]:
a.shape

torch.Size([3, 7])

In [48]:
from torch.nn import functional as F

In [50]:
?F.linear

Signature: F.linear(input, weight, bias=None)
Docstring:
Applies a linear transformation to the incoming data: :math:`y = xA^T + b`.

Shape:

    - Input: :math:`(N, *, in\_features)` where `*` means any number of
      additional dimensions
    - Weight: :math:`(out\_features, in\_features)`
    - Bias: :math:`(out\_features)`
    - Output: :math:`(N, *, out\_features)`
File:      /opt/conda/lib/python3.7/site-packages/torch/nn/functional.py
Type:      function


In [51]:
b = dz.InvLinear(7, 5)

In [53]:
b.flow(a)

tensor([[-0.5545, -1.5532, -0.2023,  1.3605,  0.9206, -0.9471,  0.8023],
        [-0.5545, -1.5532, -0.2023,  1.3605,  0.9206, -0.9471,  0.8023],
        [-0.5545, -1.5532, -0.2023,  1.3605,  0.9206, -0.9471,  0.8023]],
       grad_fn=<MmBackward>)

In [58]:
F.linear(a, torch.rand([5,7]))

tensor([[3.1820, 4.1477, 2.7423, 3.8388, 3.6860],
        [3.1820, 4.1477, 2.7423, 3.8388, 3.6860],
        [3.1820, 4.1477, 2.7423, 3.8388, 3.6860]])

In [56]:
a.shape

torch.Size([3, 7])

In [3]:
a

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [4]:
torch.sum(a, dim=-1)

tensor([7., 7., 7.])

In [5]:
torch.cat((a, a), dim=-1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

tensor([0., 0., 0., 0., 0.])

In [14]:
nn.ReLU()(a)

tensor([[0.6776, 0.3710, 0.8945, 0.8784],
        [0.4639, 0.4442, 0.4395, 0.0650],
        [0.8493, 0.2488, 0.9899, 0.1586],
        [0.7743, 0.2697, 0.1206, 0.9328],
        [0.9514, 0.9723, 0.8638, 0.8053],
        [0.4224, 0.0471, 0.0620, 0.1813],
        [0.8320, 0.7917, 0.9346, 0.3507]])

In [15]:
F.relu(a)

tensor([[0.6776, 0.3710, 0.8945, 0.8784],
        [0.4639, 0.4442, 0.4395, 0.0650],
        [0.8493, 0.2488, 0.9899, 0.1586],
        [0.7743, 0.2697, 0.1206, 0.9328],
        [0.9514, 0.9723, 0.8638, 0.8053],
        [0.4224, 0.0471, 0.0620, 0.1813],
        [0.8320, 0.7917, 0.9346, 0.3507]])

In [22]:
from torch_scatter import *

In [23]:
seg_ids = [0,0,1,1,1,2,2]

In [24]:
scatter_add(F.relu(a), torch.tensor(seg_ids), dim=0)

tensor([[1.1415, 0.8152, 1.3340, 0.9433],
        [2.5749, 1.4907, 1.9743, 1.8967],
        [1.2544, 0.8388, 0.9966, 0.5320]])

In [19]:
?scatter_add

Signature: scatter_add(src, index, dim=-1, out=None, dim_size=None, fill_value=0)
Docstring:
|

.. image:: https://raw.githubusercontent.com/rusty1s/pytorch_scatter/
        master/docs/source/_figures/add.svg?sanitize=true
    :align: center
    :width: 400px

|

Sums all values from the :attr:`src` tensor into :attr:`out` at the indices
specified in the :attr:`index` tensor along a given axis :attr:`dim`. For
each value in :attr:`src`, its output index is specified by its index in
:attr:`input` for dimensions outside of :attr:`dim` and by the
corresponding value in :attr:`index` for dimension :attr:`dim`. If
multiple indices reference the same location, their **contributions add**.

Formally, if :attr:`src` and :attr:`index` are n-dimensional tensors with
size :math:`(x_0, ..., x_{i-1}, x_i, x_{i+1}, ..., x_{n-1})` and
:attr:`dim` = `i`, then :attr:`out` must be an n-dimensional tensor with
size :math:`(x_0, ..., x_{i-1}, y, x_{i+1}, ..., x_{n-1})`. Moreover, the
values of :attr:`ind

In [21]:
?torch.index_add

Docstring: <no docstring>
Type:      builtin_function_or_method


In [11]:
a = [2,3,4]

In [12]:
for i in reversed(list(zip(a, a, a))):
    print(i)

(4, 4, 4)
(3, 3, 3)
(2, 2, 2)


In [7]:
?zip

Init signature: zip(self, /, *args, **kwargs)
Docstring:     
zip(iter1 [,iter2 [...]]) --> zip object

Return a zip object whose .__next__() method returns a tuple where
the i-th element comes from the i-th iterable argument.  The .__next__()
method continues until the shortest iterable in the argument sequence
is exhausted and then it raises StopIteration.
Type:           type
Subclasses:     
